const GET_LOCATION_REQUEST = 'HitchhikingMap/HMap/GET_LOCATION_REQUEST';
const GET_LOCATION_SUCCESS = 'HitchhikingMap/HMap/GET_LOCATION_SUCCESS';
const GET_LOCATION_FAILURE = 'HitchhikingMap/HMap/GET_LOCATION_FAILURE';

const SET_REGION = 'HitchhikingMap/HMap/SET_REGION';

const FETCH_SPOTS_REQUEST = 'HitchhikingMap/HMap/FETCH_SPOTS_REQUEST';
const FETCH_SPOTS_SUCCESS = 'HitchhikingMap/HMap/FETCH_SPOTS_SUCCESS';
const FETCH_SPOTS_FAILURE = 'HitchhikingMap/HMap/FETCH_SPOTS_FAILURE';

const SET_TUTORIAL = 'HitchhikingMap/HMap/SET_TUTORIAL'

export default {
  GET_LOCATION_REQUEST,
  GET_LOCATION_SUCCESS,
  GET_LOCATION_FAILURE,
  SET_REGION,
  FETCH_SPOTS_REQUEST,
  FETCH_SPOTS_SUCCESS,
  FETCH_SPOTS_FAILURE,
  SET_TUTORIAL,
};
