const FETCH_SPOT_DETAILS_REQUEST = 'FETCH_SPOT_DETAILS_REQUEST';
const FETCH_SPOT_DETAILS_SUCCESS = 'FETCH_SPOT_DETAILS_SUCCESS';
const FETCH_SPOT_DETAILS_FAILURE = 'FETCH_SPOT_DETAILS_FAILURE';

export default {
  FETCH_SPOT_DETAILS_REQUEST,
  FETCH_SPOT_DETAILS_SUCCESS,
  FETCH_SPOT_DETAILS_FAILURE,
};
