const FETCH_SNAPSHOTS_REQUEST = 'FETCH_SNAPSHOTS_REQUEST';
const FETCH_SNAPSHOTS_SUCCESS = 'FETCH_SNAPSHOTS_SUCCESS';
const FETCH_SNAPSHOTS_FAILURE = 'FETCH_SNAPSHOTS_FAILURE';

const SAVE_SNAPSHOT_REQUEST = 'SAVE_SNAPSHOT_REQUEST';
const SAVE_SNAPSHOT_SUCCESS = 'SAVE_SNAPSHOT_SUCCESS';
const SAVE_SNAPSHOT_FAILURE = 'SAVE_SNAPSHOT_FAILURE';

const SET_PAGE = 'SET_PAGE';

export default {
  FETCH_SNAPSHOTS_REQUEST,
  FETCH_SNAPSHOTS_SUCCESS,
  FETCH_SNAPSHOTS_FAILURE,
  SAVE_SNAPSHOT_REQUEST,
  SAVE_SNAPSHOT_SUCCESS,
  SAVE_SNAPSHOT_FAILURE,
  SET_PAGE,
}
