const SAVE_SNAPSHOT_REQUEST = 'SAVE_SNAPSHOT_REQUEST';
const SAVE_SNAPSHOT_SUCCESS = 'SAVE_SNAPSHOT_SUCCESS';
const SAVE_SNAPSHOT_FAILURE = 'SAVE_SNAPSHOT_FAILURE';

export default {
  SAVE_SNAPSHOT_REQUEST,
  SAVE_SNAPSHOT_SUCCESS,
  SAVE_SNAPSHOT_FAILURE,
};
