const SAVE_SNAPSHOT_REQUEST = 'SAVE_SNAPSHOT_REQUEST';
const SAVE_SNAPSHOT_SUCCESS = 'SAVE_SNAPSHOT_SUCCESS';
const SAVE_SNAPSHOT_FAILURE = 'SAVE_SNAPSHOT_FAILURE';

const SET_PAGE = 'SET_PAGE';

export default {
  SAVE_SNAPSHOT_REQUEST,
  SAVE_SNAPSHOT_SUCCESS,
  SAVE_SNAPSHOT_FAILURE,
  SET_PAGE,
}
