const FETCH_OFFLINE_SPOTS_REQUEST = 'FETCH_OFFLINE_SPOTS_REQUEST';
const FETCH_OFFLINE_SPOTS_SUCCESS = 'FETCH_OFFLINE_SPOTS_SUCCESS';
const FETCH_OFFLINE_SPOTS_FAILURE = 'FETCH_OFFLINE_SPOTS_FAILURE';

const FETCH_OFFLINE_SPOT_REQUEST = 'FETCH_OFFLINE_SPOT_REQUEST';
const FETCH_OFFLINE_SPOT_SUCCESS = 'FETCH_OFFLINE_SPOT_SUCCESS';
const FETCH_OFFLINE_SPOT_FAILURE = 'FETCH_OFFLINE_SPOT_FAILURE';

const SAVE_OFFLINE_SPOT_REQUEST = 'SAVE_OFFLINE_SPOT_REQUEST';
const SAVE_OFFLINE_SPOT_SUCCESS = 'SAVE_OFFLINE_SPOT_SUCCESS';
const SAVE_OFFLINE_SPOT_FAILURE = 'SAVE_OFFLINE_SPOT_FAILURE';

const DELETE_OFFLINE_SPOT_REQUEST = 'DELETE_OFFLINE_SPOT_REQUEST';
const DELETE_OFFLINE_SPOT_SUCCESS = 'DELETE_OFFLINE_SPOT_SUCCESS';
const DELETE_OFFLINE_SPOT_FAILURE = 'DELETE_OFFLINE_SPOT_FAILURE';

export default {
  FETCH_OFFLINE_SPOTS_REQUEST,
  FETCH_OFFLINE_SPOTS_SUCCESS,
  FETCH_OFFLINE_SPOTS_FAILURE,
  FETCH_OFFLINE_SPOT_REQUEST,
  FETCH_OFFLINE_SPOT_SUCCESS,
  FETCH_OFFLINE_SPOT_FAILURE,
  SAVE_OFFLINE_SPOT_REQUEST,
  SAVE_OFFLINE_SPOT_SUCCESS,
  SAVE_OFFLINE_SPOT_FAILURE,
  DELETE_OFFLINE_SPOT_REQUEST,
  DELETE_OFFLINE_SPOT_SUCCESS,
  DELETE_OFFLINE_SPOT_FAILURE,
}
