const SAVE_OFFLINE_SPOT_REQUEST = 'HitchhikingMap/OfflineSpots/SAVE_OFFLINE_SPOT_REQUEST';
const SAVE_OFFLINE_SPOT_SUCCESS = 'HitchhikingMap/OfflineSpots/SAVE_OFFLINE_SPOT_SUCCESS';
const SAVE_OFFLINE_SPOT_FAILURE = 'HitchhikingMap/OfflineSpots/SAVE_OFFLINE_SPOT_FAILURE';

export default {
  SAVE_OFFLINE_SPOT_REQUEST,
  SAVE_OFFLINE_SPOT_SUCCESS,
  SAVE_OFFLINE_SPOT_FAILURE,
}
