const SAVE_OFFLINE_SPOT = 'HitchhikingMap/OfflineSpots/SAVE_OFFLINE_SPOT';

const SAVE_STATIC_MAP_REQUEST = 'HitchhikingMap/OfflineSpots/SAVE_STATIC_MAP_REQUEST';
const SAVE_STATIC_MAP_SUCCESS = 'HitchhikingMap/OfflineSpots/SAVE_STATIC_MAP_SUCCESS';
const SAVE_STATIC_MAP_FAILURE = 'HitchhikingMap/OfflineSpots/SAVE_STATIC_MAP_FAILURE';

export default {
  SAVE_OFFLINE_SPOT,
  SAVE_STATIC_MAP_REQUEST,
  SAVE_STATIC_MAP_SUCCESS,
  SAVE_STATIC_MAP_FAILURE,
}
