const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';

const SET_REGION = 'SET_REGION';

const FETCH_SPOTS_REQUEST = 'FETCH_SPOTS_REQUEST';
const FETCH_SPOTS_SUCCESS = 'FETCH_SPOTS_SUCCESS';
const FETCH_SPOTS_FAILURE = 'FETCH_SPOTS_FAILURE';

export default {
  GET_LOCATION_REQUEST,
  GET_LOCATION_SUCCESS,
  GET_LOCATION_FAILURE,
  SET_REGION,
  FETCH_SPOTS_REQUEST,
  FETCH_SPOTS_SUCCESS,
  FETCH_SPOTS_FAILURE,
}